version: "3.8"

services:
  database:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: secret
  mails:
    image: mailhog/mailhog
    ports:
      - "25:1025"
      - "8025:8025"
